/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ies.dam.columns;

public class App extends GameApp {
  

    public static void main(String[] args) {
        launch();
    }
}
